language: python

python:
  - "2.7"
  - "3.7"
  - "3.8"

install:
  - pip install -U pip wheel
  - pip install -r requirements.txt

script:
  - pip install .
  - flake8 custom_url_avatar/*.py
  - flake8 contrib/*.py
